sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
    - uml-utilities
    - strace
script:
  - pwd
  - echo $HOME
  - git clone --depth 1 https://github.com/svn2github/bochs.git
  - cd bochs/bochs
  - ./configure --enable-cpu-level=3 --enable-ne2000 --with-term --with-nogui --enable-all-optimizations --enable-docbook=no
  - make
  - sudo make install
  - sudo setcap CAP_NET_ADMIN,CAP_NET_RAW=eip /usr/local/bin/bochs
  - cd ../../
  - printf "1\nhd\nflat\n504\ndisk.img\n" |bximage
  - touch out
  - ./do1
  - echo .
  - cat out
  - echo .
  - cat tunconfig.log
  - ps -ef
