sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
    - qemu-system
language: bash
script:
  - uname -a
  - sudo find / -name qemu*
  #- ./01*
  #- ./02*
  #- ./03*
  #- ./04*
  #- ./05*
  #- ./06*
  #- ./07*
  #- ./08*
  #- ./09*
  #- ./10*
  #- ./11*
  #- ./12*
  #- ./13*
  #- ./14*
  #- ./15*
  #- ./16*
  #- ./17*
  #- ./18*
  #- ./24*
  #- ./27*
  #- ./30*
