sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
script:
  - git clone https://github.com/svn2github/bochs.git
  - cd bochs/bochs
  - ./configure --prefix=$HOME --enable-cpu-level=3 --enable-ne2000 --with-term --with-nogui --enable-all-optimizations --enable-docbook=no
  - make
  - make install
  - cd
  - printf "hd\nflat\n504\ndisk.img\n" |bin/bximage
  - ls -ltr
  - ls -ltr /dev/net/tun
  - sudo iptables -L
  - sudo cat /proc/sys/net/ipv4/ip_forward
  - TERM=vt100 bin/bochs -f bochsrc -q
