sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
    - strace
script:
  - sudo ls -ld /srv/ftp
  - git clone --depth 1 https://github.com/svn2github/bochs.git
  - cd bochs/bochs
  - ./configure --enable-cpu-level=3 --enable-ne2000 --with-term --with-nogui --enable-all-optimizations --enable-docbook=no
  - make
  - sudo make install
  - sudo setcap CAP_NET_ADMIN,CAP_NET_RAW=eip /usr/local/bin/bochs
  - cd ../../
  - printf "1\nhd\nflat\n504\ndisk.img\n" |bximage
  - touch out
  - (until grep -q '#' out ; do sleep 5; done ; ./ghetto_slowcat.sh ./_1 4 1)|TERM=vt100 bochs -q -f bochsrc|tee -a out
  - './01. Requirements' 
