sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
language: bash
script:
  - cat /home/travis/build.sh
  - sudo ls -ld /srv/ftp
  - printf "1\nhd\nflat\n504\ndisk.img\n" |bximage
  - touch out
  - (until grep -q '#' out ; do sleep 5; done ; ./ghetto_slowcat.sh ./_1 4 1)|TERM=vt100 bochs -q -f bochsrc|tee -a out
