sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
    - uml-utilities
script:
  - pwd
  - echo $HOME
  - git clone --depth 1 https://github.com/svn2github/bochs.git
  - cd bochs/bochs
  - ./configure --prefix=$HOME --enable-cpu-level=3 --enable-ne2000 --with-term --with-nogui --enable-all-optimizations --enable-docbook=no
  - make
  - make install
  - cd ../../
  - printf "1\nhd\nflat\n504\ndisk.img\n" |~/bin/bximage
  - sudo ln -s /dev/net/tun /dev/net/tun0
  - ls -ltr /dev/net/t*
  - sudo tunctl -t tun0 -u $USER
  - echo . 
  - ls -ltr /dev/net/t*
  - sudo iptables -L
  - sudo cat /proc/sys/net/ipv4/ip_forward
  - TERM=vt100 ~/bin/bochs -f bochsrc -q
  - cat tunconfig.log
