sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
language: bash
script:
  - uname -a
  - man timer_create
  - git clone https://github.com/qemu/qemu.git
  - cd qemu
  - git reset --hard 08fd2f30bd3ee5d04596da8293689af4d4f7eb6c
  - ./configure --help
  #- ./configure --target-list=i386-softmmu --disable-sdl --disable-vnc-tls --disable-vnc-sasl --disable-vde   --extra-ldflags=-lrt
  - ./configure --target-list=i386-softmmu --disable-sdl --disable-vnc-tls --disable-vnc-sasl --disable-vde   --extra-cflags=-lrt --extra-ldflags=-lrt
  - make -d 
  #- ./01*
  #- ./02*
  #- ./03*
  #- ./04*
  #- ./05*
  #- ./06*
  #- ./07*
  #- ./08*
  #- ./09*
  #- ./10*
  #- ./11*
  #- ./12*
  #- ./13*
  #- ./14*
  #- ./15*
  #- ./16*
  #- ./17*
  #- ./18*
  #- ./24*
  #- ./27*
  #- ./30*
