sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
language: bash
script:
  - ifconfig -a
  - set
  - ./01*
  - ./02*
  - ./03*
  - ./04*
  - ./05*
  - ./06*
  - ./07*
  - ./08*
  - ./09*
  - ./10*
  - ./11*
  - ./12*
  - ./13*
  - ./14*
  - ./15*
  - ./16*
