sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
language: bash
script:
  - uname -a
  - git clone https://github.com/qemu/qemu.git
  - cd qemu
  - git reset --hard 08fd2f30bd3ee5d04596da8293689af4d4f7eb6c
  - ./configure --help
  #- ./configure --target-list=i386-softmmu --disable-sdl --disable-vnc-tls --disable-vnc-sasl --disable-vde   --extra-ldflags=-lrt
  #- ./configure --target-list=i386-softmmu --disable-sdl --disable-vnc-tls --disable-vnc-sasl --disable-vde   --extra-cflags=-lrt --extra-ldflags=-lrt
  - ./configure --target-list=i386-softmmu --disable-sdl --disable-vnc-tls --disable-vnc-sasl --disable-vde
  - fgrep -R BIT *
  - echo
  - echo ==================================================================================
  - cat Makefile
  - echo
  - echo ==================================================================================
  - make -n
  - make V=1
  - 
  - cd i386-softmmu; gcc -g -Wl,--warn-common  -m64  -o qemu vl.o osdep.o monitor.o pci.o loader.o isa_mmio.o machine.o gdbstub.o gdbstub-xml.o msix.o ioport.o virtio-blk.o virtio-balloon.o virtio-net.o virtio-console.o kvm.o kvm-all.o usb-ohci.o eepro100.o ne2000.o pcnet.o rtl8139.o e1000.o wdt_ib700.o wdt_i6300esb.o ide.o pckbd.o vga.o  sb16.o es1370.o ac97.o dma.o fdc.o mc146818rtc.o serial.o i8259.o i8254.o pcspk.o pc.o cirrus_vga.o apic.o ioapic.o parallel.o acpi.o piix_pci.o usb-uhci.o vmmouse.o vmport.o vmware_vga.o hpet.o device-hotplug.o pci-hotplug.o smbios.o -Wl,--whole-archive ../libqemu_common.a libqemu.a ../libhw64/libqemuhw64.a -Wl,--no-whole-archive  -lm -lpthread  -lz  -lutil   -lncurses -lrt; cd ..
  - make
  - echo ==================================================================================
  - cat target-i386/kvm.c
  #- ./01*
  #- ./02*
  #- ./03*
  #- ./04*
  #- ./05*
  #- ./06*
  #- ./07*
  #- ./08*
  #- ./09*
  #- ./10*
  #- ./11*
  #- ./12*
  #- ./13*
  #- ./14*
  #- ./15*
  #- ./16*
  #- ./17*
  #- ./18*
  #- ./24*
  #- ./27*
  #- ./30*
