sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
    - vsftpd
    - uml-utilities
    - strace
script:
  - pwd
  - echo $HOME
  - git clone --depth 1 https://github.com/svn2github/bochs.git
  - cd bochs/bochs
  - ./configure --enable-cpu-level=3 --enable-ne2000 --with-term --with-nogui --enable-all-optimizations --enable-docbook=no
  - make
  - sudo make install
  - cd ../../
  - printf "1\nhd\nflat\n504\ndisk.img\n" |bximage
#  - sudo ln -s /dev/net/tun /dev/net/tun0
#  - ls -ltr /dev/net/t*
#  - sudo tunctl -t tun0 -u $USER
#  - sudo tunctl -t tun -u $USER
#  - echo . 
#  - ls -ltr /dev/net/t*
#  - sudo iptables -L
#  - sudo cat /proc/sys/net/ipv4/ip_forward
  - sudo setcap CAP_NET_ADMIN,CAP_NET_RAW=eip /usr/local/bin/bochs
  - sudo getcap /usr/local/bin/bochs
  - set|grep "^LD_"
  - bochs -f bochsrc -q
  - cat tunconfig.log
